version: '3'
services:
  web:
    container_name: toriaezu-brasto-web-dev
    build:
      context: .
      dockerfile: container/development/Dockerfile
    environment:
      TZ: Asia/Tokyo
    command: rails s
    volumes:
      - .:/for_now_brainstorming
    ports:
      - "3000:3000"
    depends_on:
      - chrome
  chrome:
    container_name: toriaezu-brasto-test-chrome
    image: selenium/standalone-chrome-debug:3.141.59-fluorine
    ports:
      - "4444:4444"
      - "5900:5900"
