version: '3'
services:
  web:
    container_name: toriaezu-brasto-web-prod
    build:
      context: .
      dockerfile: container/production/Dockerfile
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
    command: rails s -p 3000
    volumes:
      - .:/for_now_brainstorming
    ports:
      - "3000:3000"
