version: '3'
services:
  web:
    container_name: toriaezu-brasto-web-prod
    build:
      context: .
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/for_now_brainstorming
    ports:
      - "3000:3000"
