version: '3'
services:
  web:
    container_name: toriaezu-brasto-web-dev
    build:
      context: .
    environment:
      TZ: Asia/Tokyo
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/for_now_brainstorming
    ports:
      - "3000:3000"
    depends_on:
      - chrome
  chrome:
    container_name: toriaezu-brasto-test-chrome
    image: selenium/standalone-chrome-debug:3.141.59-fluorine
    ports:
      - "4444:4444"
      - "5900:5900"
