version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
    command: rails s -p 3000
    volumes:
      - .:/for_now_brainstorming
    ports:
      - "80:3000"
