version: '3'
services:
  web:
    container_name: toriaezu-brasto-web-dev
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    environment:
      TZ: Asia/Tokyo
    command: rails s
    volumes:
      - .:/for_now_brainstorming
    ports:
      - "3000:3000"
