version: '3'
services:
  web:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    environment:
      RAILS_ENV: production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/for_now_brainstorming
    ports:
      - "3000:3000"
